# ~/.git-hooks/pre-commit-config.toml
# Configuration for the universal pre-commit hook

[rust]
# Enable/disable specific checks
enable_fmt = true
enable_typos = true
enable_clippy = true
enable_test = false

# Additional cargo fmt arguments
fmt_args = ["--all", "-q", "--check", "--message-format=short"]

# Additional typos arguments  
typos_args = []

# Additional clippy arguments (when enabled)
clippy_args = [
  "--all",
  "--all-targets",
  "-q",
  "--message-format=short",
  "--",
  "-D",
  "warnings",
]

# Paths to ignore (relative to repository root)
ignore_paths = ["target/", "vendor/", ".git/"]

[general]
# Show verbose output
verbose = true

# Fail fast on first error
fail_fast = true

# Allow commits even if optional tools are missing
allow_missing_tools = true
